[build]
builder = "nixpacks"

[deploy]
startCommand = "cd ml_backend && python start_railway.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
FLASK_DEBUG = "False"
PORT = "5000"
HOST = "0.0.0.0"
